// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/boletas/data/repositories/boletas_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cssayp_movil/auth/data/datasources/secure_storage_data_source.dart'
    as _i5;
import 'package:cssayp_movil/boletas/boletas.dart' as _i4;
import 'package:cssayp_movil/boletas/data/models/paginated_response_model.dart'
    as _i3;
import 'package:cssayp_movil/shared/services/jwt_token_service.dart' as _i8;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponseModel_1 extends _i1.SmartFake
    implements _i3.PaginatedResponseModel {
  _FakePaginatedResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBoletaEntity_2 extends _i1.SmartFake implements _i4.BoletaEntity {
  _FakeBoletaEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorageDataSource_3 extends _i1.SmartFake
    implements _i5.SecureStorageDataSource {
  _FakeSecureStorageDataSource_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BoletasDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoletasDataSource extends _i1.Mock implements _i4.BoletasDataSource {
  MockBoletasDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.Future<_i4.CrearBoletaResponse> crearBoletaInicio({
    required String? token,
    required String? caratula,
    required String? juzgado,
    required _i4.CircunscripcionEntity? circunscripcion,
    required _i4.TipoJuicioEntity? tipoJuicio,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearBoletaInicio, [], {
              #token: token,
              #caratula: caratula,
              #juzgado: juzgado,
              #circunscripcion: circunscripcion,
              #tipoJuicio: tipoJuicio,
            }),
            returnValue: _i6.Future<_i4.CrearBoletaResponse>.value(
              _i7.dummyValue<_i4.CrearBoletaResponse>(
                this,
                Invocation.method(#crearBoletaInicio, [], {
                  #token: token,
                  #caratula: caratula,
                  #juzgado: juzgado,
                  #circunscripcion: circunscripcion,
                  #tipoJuicio: tipoJuicio,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.CrearBoletaResponse>);

  @override
  _i6.Future<_i4.CrearBoletaResponse> crearBoletaFinalizacion({
    required int? nroAfiliado,
    required String? digito,
    required String? caratula,
    required int? idBoletaInicio,
    required double? monto,
    required DateTime? fechaRegulacion,
    required double? honorarios,
    required double? cantidadJus,
    required double? valorJus,
    int? nroExpediente,
    int? anioExpediente,
    int? cuij,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearBoletaFinalizacion, [], {
              #nroAfiliado: nroAfiliado,
              #digito: digito,
              #caratula: caratula,
              #idBoletaInicio: idBoletaInicio,
              #monto: monto,
              #fechaRegulacion: fechaRegulacion,
              #honorarios: honorarios,
              #cantidadJus: cantidadJus,
              #valorJus: valorJus,
              #nroExpediente: nroExpediente,
              #anioExpediente: anioExpediente,
              #cuij: cuij,
            }),
            returnValue: _i6.Future<_i4.CrearBoletaResponse>.value(
              _i7.dummyValue<_i4.CrearBoletaResponse>(
                this,
                Invocation.method(#crearBoletaFinalizacion, [], {
                  #nroAfiliado: nroAfiliado,
                  #digito: digito,
                  #caratula: caratula,
                  #idBoletaInicio: idBoletaInicio,
                  #monto: monto,
                  #fechaRegulacion: fechaRegulacion,
                  #honorarios: honorarios,
                  #cantidadJus: cantidadJus,
                  #valorJus: valorJus,
                  #nroExpediente: nroExpediente,
                  #anioExpediente: anioExpediente,
                  #cuij: cuij,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.CrearBoletaResponse>);

  @override
  _i6.Future<_i4.HistorialBoletasResponse> obtenerHistorialBoletas({
    required int? nroAfiliado,
    int? page,
    int? mostrarPagadas = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerHistorialBoletas, [], {
              #nroAfiliado: nroAfiliado,
              #page: page,
              #mostrarPagadas: mostrarPagadas,
            }),
            returnValue: _i6.Future<_i4.HistorialBoletasResponse>.value(
              _i7.dummyValue<_i4.HistorialBoletasResponse>(
                this,
                Invocation.method(#obtenerHistorialBoletas, [], {
                  #nroAfiliado: nroAfiliado,
                  #page: page,
                  #mostrarPagadas: mostrarPagadas,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.HistorialBoletasResponse>);

  @override
  _i6.Future<Map<String, dynamic>> obtenerParametrosBoletaInicio(
    int? nroAfiliado,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerParametrosBoletaInicio, [nroAfiliado]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i3.PaginatedResponseModel> buscarBoletasInicioPagadas({
    required int? nroAfiliado,
    int? page = 1,
    String? caratulaBuscada,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buscarBoletasInicioPagadas, [], {
              #nroAfiliado: nroAfiliado,
              #page: page,
              #caratulaBuscada: caratulaBuscada,
            }),
            returnValue: _i6.Future<_i3.PaginatedResponseModel>.value(
              _FakePaginatedResponseModel_1(
                this,
                Invocation.method(#buscarBoletasInicioPagadas, [], {
                  #nroAfiliado: nroAfiliado,
                  #page: page,
                  #caratulaBuscada: caratulaBuscada,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.PaginatedResponseModel>);
}

/// A class which mocks [BoletasLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoletasLocalDataSource extends _i1.Mock
    implements _i4.BoletasLocalDataSource {
  MockBoletasLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> guardarBoletas(List<_i4.BoletaEntity>? boletas) =>
      (super.noSuchMethod(
            Invocation.method(#guardarBoletas, [boletas]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.BoletaEntity>> obtenerBoletasLocales({
    int? limit,
    int? offset,
    String? caratulaFiltro,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerBoletasLocales, [], {
              #limit: limit,
              #offset: offset,
              #caratulaFiltro: caratulaFiltro,
            }),
            returnValue: _i6.Future<List<_i4.BoletaEntity>>.value(
              <_i4.BoletaEntity>[],
            ),
          )
          as _i6.Future<List<_i4.BoletaEntity>>);

  @override
  _i6.Future<int> obtenerConteoBoletasLocales({String? caratulaFiltro}) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerConteoBoletasLocales, [], {
              #caratulaFiltro: caratulaFiltro,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> limpiarCache() =>
      (super.noSuchMethod(
            Invocation.method(#limpiarCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<DateTime?> obtenerUltimaSincronizacion() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerUltimaSincronizacion, []),
            returnValue: _i6.Future<DateTime?>.value(),
          )
          as _i6.Future<DateTime?>);

  @override
  _i6.Future<bool> tieneBoletasEnCache() =>
      (super.noSuchMethod(
            Invocation.method(#tieneBoletasEnCache, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  Map<String, dynamic> boletaToMap(_i4.BoletaEntity? boleta) =>
      (super.noSuchMethod(
            Invocation.method(#boletaToMap, [boleta]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.BoletaEntity mapToBoleta(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#mapToBoleta, [map]),
            returnValue: _FakeBoletaEntity_2(
              this,
              Invocation.method(#mapToBoleta, [map]),
            ),
          )
          as _i4.BoletaEntity);

  @override
  _i4.BoletaTipo stringToBoletaTipo(String? tipo) =>
      (super.noSuchMethod(
            Invocation.method(#stringToBoletaTipo, [tipo]),
            returnValue: _i4.BoletaTipo.inicio,
          )
          as _i4.BoletaTipo);
}

/// A class which mocks [JwtTokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJwtTokenService extends _i1.Mock implements _i8.JwtTokenService {
  MockJwtTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SecureStorageDataSource get secureStorageDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorageDataSource),
            returnValue: _FakeSecureStorageDataSource_3(
              this,
              Invocation.getter(#secureStorageDataSource),
            ),
          )
          as _i5.SecureStorageDataSource);

  @override
  _i6.Future<String?> obtenerToken() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> obtenerCampo(String? campo) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerCampo, [campo]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> obtenerDigito() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerDigito, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> obtenerNumeroAfiliado() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerNumeroAfiliado, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, dynamic>?> obtenerPayloadCompleto() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerPayloadCompleto, []),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);
}
