// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/boletas/data/repositories/boletas_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cssayp_movil/auth/data/datasources/secure_storage_data_source.dart'
    as _i6;
import 'package:cssayp_movil/boletas/boletas.dart' as _i5;
import 'package:cssayp_movil/boletas/data/models/juicios_abiertos_response.dart'
    as _i4;
import 'package:cssayp_movil/boletas/data/models/paginated_response_model.dart'
    as _i3;
import 'package:cssayp_movil/shared/services/jwt_token_service.dart' as _i9;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponseModel_1 extends _i1.SmartFake
    implements _i3.PaginatedResponseModel {
  _FakePaginatedResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJuiciosAbiertosPaginatedResponse_2 extends _i1.SmartFake
    implements _i4.JuiciosAbiertosPaginatedResponse {
  _FakeJuiciosAbiertosPaginatedResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBoletaEntity_3 extends _i1.SmartFake implements _i5.BoletaEntity {
  _FakeBoletaEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorageDataSource_4 extends _i1.SmartFake
    implements _i6.SecureStorageDataSource {
  _FakeSecureStorageDataSource_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BoletasDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoletasDataSource extends _i1.Mock implements _i5.BoletasDataSource {
  MockBoletasDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i7.Future<_i5.CrearBoletaResponse> crearBoletaInicio({
    required String? token,
    required String? caratula,
    required String? juzgado,
    required _i5.CircunscripcionEntity? circunscripcion,
    required _i5.TipoJuicioEntity? tipoJuicio,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearBoletaInicio, [], {
              #token: token,
              #caratula: caratula,
              #juzgado: juzgado,
              #circunscripcion: circunscripcion,
              #tipoJuicio: tipoJuicio,
            }),
            returnValue: _i7.Future<_i5.CrearBoletaResponse>.value(
              _i8.dummyValue<_i5.CrearBoletaResponse>(
                this,
                Invocation.method(#crearBoletaInicio, [], {
                  #token: token,
                  #caratula: caratula,
                  #juzgado: juzgado,
                  #circunscripcion: circunscripcion,
                  #tipoJuicio: tipoJuicio,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.CrearBoletaResponse>);

  @override
  _i7.Future<_i5.CrearBoletaResponse> crearBoletaFinalizacion({
    required int? nroAfiliado,
    required String? digito,
    required String? caratula,
    required int? idBoletaInicio,
    required double? monto,
    required DateTime? fechaRegulacion,
    required double? honorarios,
    required double? cantidadJus,
    required double? valorJus,
    int? nroExpediente,
    int? anioExpediente,
    int? cuij,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearBoletaFinalizacion, [], {
              #nroAfiliado: nroAfiliado,
              #digito: digito,
              #caratula: caratula,
              #idBoletaInicio: idBoletaInicio,
              #monto: monto,
              #fechaRegulacion: fechaRegulacion,
              #honorarios: honorarios,
              #cantidadJus: cantidadJus,
              #valorJus: valorJus,
              #nroExpediente: nroExpediente,
              #anioExpediente: anioExpediente,
              #cuij: cuij,
            }),
            returnValue: _i7.Future<_i5.CrearBoletaResponse>.value(
              _i8.dummyValue<_i5.CrearBoletaResponse>(
                this,
                Invocation.method(#crearBoletaFinalizacion, [], {
                  #nroAfiliado: nroAfiliado,
                  #digito: digito,
                  #caratula: caratula,
                  #idBoletaInicio: idBoletaInicio,
                  #monto: monto,
                  #fechaRegulacion: fechaRegulacion,
                  #honorarios: honorarios,
                  #cantidadJus: cantidadJus,
                  #valorJus: valorJus,
                  #nroExpediente: nroExpediente,
                  #anioExpediente: anioExpediente,
                  #cuij: cuij,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.CrearBoletaResponse>);

  @override
  _i7.Future<_i5.HistorialBoletasResponse> obtenerHistorialBoletas({
    required int? nroAfiliado,
    int? page,
    String? filtroEstado = 'todas',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerHistorialBoletas, [], {
              #nroAfiliado: nroAfiliado,
              #page: page,
              #filtroEstado: filtroEstado,
            }),
            returnValue: _i7.Future<_i5.HistorialBoletasResponse>.value(
              _i8.dummyValue<_i5.HistorialBoletasResponse>(
                this,
                Invocation.method(#obtenerHistorialBoletas, [], {
                  #nroAfiliado: nroAfiliado,
                  #page: page,
                  #filtroEstado: filtroEstado,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.HistorialBoletasResponse>);

  @override
  _i7.Future<Map<String, dynamic>> obtenerParametrosBoletaInicio(
    int? nroAfiliado,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerParametrosBoletaInicio, [nroAfiliado]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i3.PaginatedResponseModel> buscarBoletasInicioPagadas({
    required int? nroAfiliado,
    int? page = 1,
    String? caratulaBuscada,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buscarBoletasInicioPagadas, [], {
              #nroAfiliado: nroAfiliado,
              #page: page,
              #caratulaBuscada: caratulaBuscada,
            }),
            returnValue: _i7.Future<_i3.PaginatedResponseModel>.value(
              _FakePaginatedResponseModel_1(
                this,
                Invocation.method(#buscarBoletasInicioPagadas, [], {
                  #nroAfiliado: nroAfiliado,
                  #page: page,
                  #caratulaBuscada: caratulaBuscada,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.PaginatedResponseModel>);

  @override
  _i7.Future<_i4.JuiciosAbiertosPaginatedResponse> obtenerJuiciosAbiertos({
    required int? nroAfiliado,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerJuiciosAbiertos, [], {
              #nroAfiliado: nroAfiliado,
              #page: page,
            }),
            returnValue: _i7.Future<_i4.JuiciosAbiertosPaginatedResponse>.value(
              _FakeJuiciosAbiertosPaginatedResponse_2(
                this,
                Invocation.method(#obtenerJuiciosAbiertos, [], {
                  #nroAfiliado: nroAfiliado,
                  #page: page,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.JuiciosAbiertosPaginatedResponse>);
}

/// A class which mocks [BoletasLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoletasLocalDataSource extends _i1.Mock
    implements _i5.BoletasLocalDataSource {
  MockBoletasLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> guardarBoletas(List<_i5.BoletaEntity>? boletas) =>
      (super.noSuchMethod(
            Invocation.method(#guardarBoletas, [boletas]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.BoletaEntity>> obtenerBoletasLocales({
    int? limit,
    int? offset,
    String? caratulaFiltro,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerBoletasLocales, [], {
              #limit: limit,
              #offset: offset,
              #caratulaFiltro: caratulaFiltro,
            }),
            returnValue: _i7.Future<List<_i5.BoletaEntity>>.value(
              <_i5.BoletaEntity>[],
            ),
          )
          as _i7.Future<List<_i5.BoletaEntity>>);

  @override
  _i7.Future<int> obtenerConteoBoletasLocales({String? caratulaFiltro}) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerConteoBoletasLocales, [], {
              #caratulaFiltro: caratulaFiltro,
            }),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> limpiarCache() =>
      (super.noSuchMethod(
            Invocation.method(#limpiarCache, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<DateTime?> obtenerUltimaSincronizacion() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerUltimaSincronizacion, []),
            returnValue: _i7.Future<DateTime?>.value(),
          )
          as _i7.Future<DateTime?>);

  @override
  _i7.Future<bool> tieneBoletasEnCache() =>
      (super.noSuchMethod(
            Invocation.method(#tieneBoletasEnCache, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  Map<String, dynamic> boletaToMap(_i5.BoletaEntity? boleta) =>
      (super.noSuchMethod(
            Invocation.method(#boletaToMap, [boleta]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.BoletaEntity mapToBoleta(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#mapToBoleta, [map]),
            returnValue: _FakeBoletaEntity_3(
              this,
              Invocation.method(#mapToBoleta, [map]),
            ),
          )
          as _i5.BoletaEntity);
}

/// A class which mocks [JwtTokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJwtTokenService extends _i1.Mock implements _i9.JwtTokenService {
  MockJwtTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.SecureStorageDataSource get secureStorageDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorageDataSource),
            returnValue: _FakeSecureStorageDataSource_4(
              this,
              Invocation.getter(#secureStorageDataSource),
            ),
          )
          as _i6.SecureStorageDataSource);

  @override
  _i7.Future<String?> obtenerToken() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerToken, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> obtenerCampo(String? campo) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerCampo, [campo]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> obtenerDigito() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerDigito, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> obtenerNumeroAfiliado() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerNumeroAfiliado, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, dynamic>?> obtenerPayloadCompleto() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerPayloadCompleto, []),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);
}
