// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/pagos/presentation/providers/red_link_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cssayp_movil/pagos/data/models/red_link_payment_response_model.dart'
    as _i3;
import 'package:cssayp_movil/pagos/domain/repositories/red_link_repository.dart'
    as _i2;
import 'package:cssayp_movil/pagos/domain/usecases/pagar_con_red_link_use_case.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRedLinkRepository_0 extends _i1.SmartFake
    implements _i2.RedLinkRepository {
  _FakeRedLinkRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRedLinkPaymentResponseModel_1 extends _i1.SmartFake
    implements _i3.RedLinkPaymentResponseModel {
  _FakeRedLinkPaymentResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRedLinkPaymentStatusModel_2 extends _i1.SmartFake
    implements _i3.RedLinkPaymentStatusModel {
  _FakeRedLinkPaymentStatusModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PagarConRedLinkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPagarConRedLinkUseCase extends _i1.Mock
    implements _i4.PagarConRedLinkUseCase {
  MockPagarConRedLinkUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RedLinkRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRedLinkRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RedLinkRepository);

  @override
  _i5.Future<_i3.RedLinkPaymentResponseModel> iniciarPago({
    required int? idBoleta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#iniciarPago, [], {#idBoleta: idBoleta}),
            returnValue: _i5.Future<_i3.RedLinkPaymentResponseModel>.value(
              _FakeRedLinkPaymentResponseModel_1(
                this,
                Invocation.method(#iniciarPago, [], {#idBoleta: idBoleta}),
              ),
            ),
          )
          as _i5.Future<_i3.RedLinkPaymentResponseModel>);

  @override
  _i5.Stream<_i3.RedLinkPaymentStatusModel> monitorearPago({
    required int? idBoleta,
    Duration? intervalo = const Duration(seconds: 5),
    int? maxIntentos,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#monitorearPago, [], {
              #idBoleta: idBoleta,
              #intervalo: intervalo,
              #maxIntentos: maxIntentos,
            }),
            returnValue: _i5.Stream<_i3.RedLinkPaymentStatusModel>.empty(),
          )
          as _i5.Stream<_i3.RedLinkPaymentStatusModel>);

  @override
  _i5.Future<_i3.RedLinkPaymentStatusModel> verificarEstado({
    required int? idBoleta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verificarEstado, [], {#idBoleta: idBoleta}),
            returnValue: _i5.Future<_i3.RedLinkPaymentStatusModel>.value(
              _FakeRedLinkPaymentStatusModel_2(
                this,
                Invocation.method(#verificarEstado, [], {#idBoleta: idBoleta}),
              ),
            ),
          )
          as _i5.Future<_i3.RedLinkPaymentStatusModel>);
}
