// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/notificaciones/domain/usecases/marcar_notificaciones_leidas_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cssayp_movil/auth/data/models/cambiar_password_response_models.dart'
    as _i10;
import 'package:cssayp_movil/auth/data/models/recuperar_password_response_models.dart'
    as _i8;
import 'package:cssayp_movil/auth/domain/entities/usuario_entity.dart' as _i7;
import 'package:cssayp_movil/auth/domain/repositories/usuario_repository.dart'
    as _i6;
import 'package:cssayp_movil/notificaciones/domain/entities/notificacion_entity.dart'
    as _i5;
import 'package:cssayp_movil/notificaciones/domain/repositories/notificaciones_repository.dart'
    as _i3;
import 'package:cssayp_movil/shared/models/paginated_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificacionesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificacionesRepository extends _i1.Mock
    implements _i3.NotificacionesRepository {
  MockNotificacionesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginatedResponse<_i5.NotificacionEntity>>
  obtenerNotificaciones(int? nroAfiliado) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerNotificaciones, [nroAfiliado]),
            returnValue:
                _i4.Future<_i2.PaginatedResponse<_i5.NotificacionEntity>>.value(
                  _FakePaginatedResponse_0<_i5.NotificacionEntity>(
                    this,
                    Invocation.method(#obtenerNotificaciones, [nroAfiliado]),
                  ),
                ),
          )
          as _i4.Future<_i2.PaginatedResponse<_i5.NotificacionEntity>>);

  @override
  _i4.Future<void> registrarDispositivo(
    String? token,
    int? nroAfiliado,
    String? nombreDispositivo,
    String? plataforma,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registrarDispositivo, [
              token,
              nroAfiliado,
              nombreDispositivo,
              plataforma,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> marcarNotificacionesComoLeidas(
    List<String>? uuidList,
    int? nroAfiliado,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#marcarNotificacionesComoLeidas, [
              uuidList,
              nroAfiliado,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UsuarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuarioRepository extends _i1.Mock implements _i6.UsuarioRepository {
  MockUsuarioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.UsuarioEntity?> autenticar(
    String? usuario,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#autenticar, [usuario, password]),
            returnValue: _i4.Future<_i7.UsuarioEntity?>.value(),
          )
          as _i4.Future<_i7.UsuarioEntity?>);

  @override
  _i4.Future<bool> estaAutenticado() =>
      (super.noSuchMethod(
            Invocation.method(#estaAutenticado, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> cerrarSesion() =>
      (super.noSuchMethod(
            Invocation.method(#cerrarSesion, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.UsuarioEntity?> obtenerUsuarioActual() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerUsuarioActual, []),
            returnValue: _i4.Future<_i7.UsuarioEntity?>.value(),
          )
          as _i4.Future<_i7.UsuarioEntity?>);

  @override
  _i4.Future<_i8.RecuperarResponseModel> recuperarPassword(
    String? tipoDocumento,
    String? nroDocumento,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recuperarPassword, [
              tipoDocumento,
              nroDocumento,
              email,
            ]),
            returnValue: _i4.Future<_i8.RecuperarResponseModel>.value(
              _i9.dummyValue<_i8.RecuperarResponseModel>(
                this,
                Invocation.method(#recuperarPassword, [
                  tipoDocumento,
                  nroDocumento,
                  email,
                ]),
              ),
            ),
          )
          as _i4.Future<_i8.RecuperarResponseModel>);

  @override
  _i4.Future<_i10.CambiarPasswordResponseModel> cambiarPassword(
    String? passwordActual,
    String? passwordNueva,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cambiarPassword, [
              passwordActual,
              passwordNueva,
            ]),
            returnValue: _i4.Future<_i10.CambiarPasswordResponseModel>.value(
              _i9.dummyValue<_i10.CambiarPasswordResponseModel>(
                this,
                Invocation.method(#cambiarPassword, [
                  passwordActual,
                  passwordNueva,
                ]),
              ),
            ),
          )
          as _i4.Future<_i10.CambiarPasswordResponseModel>);
}
