// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/comprobantes/presentation/providers/comprobantes_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cssayp_movil/comprobantes/comprobantes.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeComprobantesRepository_0 extends _i1.SmartFake
    implements _i2.ComprobantesRepository {
  _FakeComprobantesRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComprobanteEntity_1 extends _i1.SmartFake
    implements _i2.ComprobanteEntity {
  _FakeComprobanteEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ObtenerComprobanteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObtenerComprobanteUseCase extends _i1.Mock
    implements _i2.ObtenerComprobanteUseCase {
  @override
  _i2.ComprobantesRepository get comprobantesRepository =>
      (super.noSuchMethod(
            Invocation.getter(#comprobantesRepository),
            returnValue: _FakeComprobantesRepository_0(
              this,
              Invocation.getter(#comprobantesRepository),
            ),
            returnValueForMissingStub: _FakeComprobantesRepository_0(
              this,
              Invocation.getter(#comprobantesRepository),
            ),
          )
          as _i2.ComprobantesRepository);

  @override
  _i3.Future<_i2.ComprobanteEntity> execute(int? idBoletaPagada) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [idBoletaPagada]),
            returnValue: _i3.Future<_i2.ComprobanteEntity>.value(
              _FakeComprobanteEntity_1(
                this,
                Invocation.method(#execute, [idBoletaPagada]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.ComprobanteEntity>.value(
              _FakeComprobanteEntity_1(
                this,
                Invocation.method(#execute, [idBoletaPagada]),
              ),
            ),
          )
          as _i3.Future<_i2.ComprobanteEntity>);
}
