// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/boletas/presentation/providers/boleta_inicio_data_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cssayp_movil/auth/auth.dart' as _i3;
import 'package:cssayp_movil/boletas/boletas.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBoletasRepository_0 extends _i1.SmartFake
    implements _i2.BoletasRepository {
  _FakeBoletasRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsuarioRepository_1 extends _i1.SmartFake
    implements _i3.UsuarioRepository {
  _FakeUsuarioRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParametrosBoletaInicioEntity_2 extends _i1.SmartFake
    implements _i2.ParametrosBoletaInicioEntity {
  _FakeParametrosBoletaInicioEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [ObtenerParametrosBoletaInicioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObtenerParametrosBoletaInicioUseCase extends _i1.Mock
    implements _i2.ObtenerParametrosBoletaInicioUseCase {
  @override
  _i2.BoletasRepository get boletasRepository =>
      (super.noSuchMethod(
            Invocation.getter(#boletasRepository),
            returnValue: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
            returnValueForMissingStub: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
          )
          as _i2.BoletasRepository);

  @override
  _i3.UsuarioRepository get usuarioRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuarioRepository),
            returnValue: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
            returnValueForMissingStub: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
          )
          as _i3.UsuarioRepository);

  @override
  _i4.Future<_i2.ParametrosBoletaInicioEntity> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i2.ParametrosBoletaInicioEntity>.value(
              _FakeParametrosBoletaInicioEntity_2(
                this,
                Invocation.method(#execute, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ParametrosBoletaInicioEntity>.value(
                  _FakeParametrosBoletaInicioEntity_2(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ParametrosBoletaInicioEntity>);
}
