// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/boletas/presentation/providers/boletas_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cssayp_movil/auth/auth.dart' as _i3;
import 'package:cssayp_movil/boletas/data/datasources/boletas_local_data_source.dart'
    as _i12;
import 'package:cssayp_movil/boletas/data/models/historial_boletas_response_models.dart'
    as _i4;
import 'package:cssayp_movil/boletas/data/models/paginated_response_model.dart'
    as _i6;
import 'package:cssayp_movil/boletas/domain/entities/boleta_entity.dart' as _i5;
import 'package:cssayp_movil/boletas/domain/entities/boleta_tipo.dart' as _i13;
import 'package:cssayp_movil/boletas/domain/repositories/boletas_repository.dart'
    as _i2;
import 'package:cssayp_movil/boletas/domain/usecases/buscar_boletas_inicio_pagadas_use_case.dart'
    as _i11;
import 'package:cssayp_movil/boletas/domain/usecases/generar_boleta_finalizacion_use_case.dart'
    as _i10;
import 'package:cssayp_movil/boletas/domain/usecases/generar_boleta_inicio_use_case.dart'
    as _i9;
import 'package:cssayp_movil/boletas/domain/usecases/obtener_historial_boletas_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBoletasRepository_0 extends _i1.SmartFake
    implements _i2.BoletasRepository {
  _FakeBoletasRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsuarioRepository_1 extends _i1.SmartFake
    implements _i3.UsuarioRepository {
  _FakeUsuarioRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistorialBoletasSuccessResponse_2 extends _i1.SmartFake
    implements _i4.HistorialBoletasSuccessResponse {
  _FakeHistorialBoletasSuccessResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBoletaEntity_3 extends _i1.SmartFake implements _i5.BoletaEntity {
  _FakeBoletaEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponseModel_4 extends _i1.SmartFake
    implements _i6.PaginatedResponseModel {
  _FakePaginatedResponseModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ObtenerHistorialBoletasUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObtenerHistorialBoletasUseCase extends _i1.Mock
    implements _i7.ObtenerHistorialBoletasUseCase {
  @override
  _i2.BoletasRepository get boletasRepository =>
      (super.noSuchMethod(
            Invocation.getter(#boletasRepository),
            returnValue: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
            returnValueForMissingStub: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
          )
          as _i2.BoletasRepository);

  @override
  _i3.UsuarioRepository get usuarioRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuarioRepository),
            returnValue: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
            returnValueForMissingStub: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
          )
          as _i3.UsuarioRepository);

  @override
  _i8.Future<_i4.HistorialBoletasSuccessResponse> execute({int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#page: page}),
            returnValue: _i8.Future<_i4.HistorialBoletasSuccessResponse>.value(
              _FakeHistorialBoletasSuccessResponse_2(
                this,
                Invocation.method(#execute, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.HistorialBoletasSuccessResponse>.value(
                  _FakeHistorialBoletasSuccessResponse_2(
                    this,
                    Invocation.method(#execute, [], {#page: page}),
                  ),
                ),
          )
          as _i8.Future<_i4.HistorialBoletasSuccessResponse>);
}

/// A class which mocks [GenerarBoletaInicioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerarBoletaInicioUseCase extends _i1.Mock
    implements _i9.GenerarBoletaInicioUseCase {
  @override
  _i2.BoletasRepository get boletasRepository =>
      (super.noSuchMethod(
            Invocation.getter(#boletasRepository),
            returnValue: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
            returnValueForMissingStub: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
          )
          as _i2.BoletasRepository);

  @override
  _i3.UsuarioRepository get usuarioRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuarioRepository),
            returnValue: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
            returnValueForMissingStub: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
          )
          as _i3.UsuarioRepository);

  @override
  _i8.Future<_i5.BoletaEntity> execute({
    required String? caratula,
    required double? monto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #caratula: caratula,
              #monto: monto,
            }),
            returnValue: _i8.Future<_i5.BoletaEntity>.value(
              _FakeBoletaEntity_3(
                this,
                Invocation.method(#execute, [], {
                  #caratula: caratula,
                  #monto: monto,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.BoletaEntity>.value(
              _FakeBoletaEntity_3(
                this,
                Invocation.method(#execute, [], {
                  #caratula: caratula,
                  #monto: monto,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.BoletaEntity>);
}

/// A class which mocks [GenerarBoletaFinalizacionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerarBoletaFinalizacionUseCase extends _i1.Mock
    implements _i10.GenerarBoletaFinalizacionUseCase {
  @override
  _i2.BoletasRepository get boletasRepository =>
      (super.noSuchMethod(
            Invocation.getter(#boletasRepository),
            returnValue: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
            returnValueForMissingStub: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
          )
          as _i2.BoletasRepository);

  @override
  _i3.UsuarioRepository get usuarioRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuarioRepository),
            returnValue: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
            returnValueForMissingStub: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
          )
          as _i3.UsuarioRepository);

  @override
  _i8.Future<_i5.BoletaEntity> execute({
    required int? idBoletaInicio,
    required double? monto,
    required DateTime? fechaRegulacion,
    required double? honorarios,
    required String? caratula,
    required double? cantidadJus,
    required double? valorJus,
    int? nroExpediente,
    int? anioExpediente,
    int? cuij,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #idBoletaInicio: idBoletaInicio,
              #monto: monto,
              #fechaRegulacion: fechaRegulacion,
              #honorarios: honorarios,
              #caratula: caratula,
              #cantidadJus: cantidadJus,
              #valorJus: valorJus,
              #nroExpediente: nroExpediente,
              #anioExpediente: anioExpediente,
              #cuij: cuij,
            }),
            returnValue: _i8.Future<_i5.BoletaEntity>.value(
              _FakeBoletaEntity_3(
                this,
                Invocation.method(#execute, [], {
                  #idBoletaInicio: idBoletaInicio,
                  #monto: monto,
                  #fechaRegulacion: fechaRegulacion,
                  #honorarios: honorarios,
                  #caratula: caratula,
                  #cantidadJus: cantidadJus,
                  #valorJus: valorJus,
                  #nroExpediente: nroExpediente,
                  #anioExpediente: anioExpediente,
                  #cuij: cuij,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.BoletaEntity>.value(
              _FakeBoletaEntity_3(
                this,
                Invocation.method(#execute, [], {
                  #idBoletaInicio: idBoletaInicio,
                  #monto: monto,
                  #fechaRegulacion: fechaRegulacion,
                  #honorarios: honorarios,
                  #caratula: caratula,
                  #cantidadJus: cantidadJus,
                  #valorJus: valorJus,
                  #nroExpediente: nroExpediente,
                  #anioExpediente: anioExpediente,
                  #cuij: cuij,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.BoletaEntity>);
}

/// A class which mocks [BuscarBoletasInicioPagadasUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuscarBoletasInicioPagadasUseCase extends _i1.Mock
    implements _i11.BuscarBoletasInicioPagadasUseCase {
  @override
  _i2.BoletasRepository get boletasRepository =>
      (super.noSuchMethod(
            Invocation.getter(#boletasRepository),
            returnValue: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
            returnValueForMissingStub: _FakeBoletasRepository_0(
              this,
              Invocation.getter(#boletasRepository),
            ),
          )
          as _i2.BoletasRepository);

  @override
  _i3.UsuarioRepository get usuarioRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuarioRepository),
            returnValue: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
            returnValueForMissingStub: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
          )
          as _i3.UsuarioRepository);

  @override
  _i8.Future<_i6.PaginatedResponseModel> execute({
    int? page = 1,
    String? caratulaBuscada,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #page: page,
              #caratulaBuscada: caratulaBuscada,
            }),
            returnValue: _i8.Future<_i6.PaginatedResponseModel>.value(
              _FakePaginatedResponseModel_4(
                this,
                Invocation.method(#execute, [], {
                  #page: page,
                  #caratulaBuscada: caratulaBuscada,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i6.PaginatedResponseModel>.value(
                  _FakePaginatedResponseModel_4(
                    this,
                    Invocation.method(#execute, [], {
                      #page: page,
                      #caratulaBuscada: caratulaBuscada,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i6.PaginatedResponseModel>);
}

/// A class which mocks [BoletasLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoletasLocalDataSource extends _i1.Mock
    implements _i12.BoletasLocalDataSource {
  @override
  _i8.Future<void> guardarBoletas(List<_i5.BoletaEntity>? boletas) =>
      (super.noSuchMethod(
            Invocation.method(#guardarBoletas, [boletas]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i5.BoletaEntity>> obtenerBoletasLocales({
    int? limit,
    int? offset,
    String? caratulaFiltro,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerBoletasLocales, [], {
              #limit: limit,
              #offset: offset,
              #caratulaFiltro: caratulaFiltro,
            }),
            returnValue: _i8.Future<List<_i5.BoletaEntity>>.value(
              <_i5.BoletaEntity>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i5.BoletaEntity>>.value(
              <_i5.BoletaEntity>[],
            ),
          )
          as _i8.Future<List<_i5.BoletaEntity>>);

  @override
  _i8.Future<int> obtenerConteoBoletasLocales({String? caratulaFiltro}) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerConteoBoletasLocales, [], {
              #caratulaFiltro: caratulaFiltro,
            }),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> limpiarCache() =>
      (super.noSuchMethod(
            Invocation.method(#limpiarCache, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<DateTime?> obtenerUltimaSincronizacion() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerUltimaSincronizacion, []),
            returnValue: _i8.Future<DateTime?>.value(),
            returnValueForMissingStub: _i8.Future<DateTime?>.value(),
          )
          as _i8.Future<DateTime?>);

  @override
  _i8.Future<bool> tieneBoletasEnCache() =>
      (super.noSuchMethod(
            Invocation.method(#tieneBoletasEnCache, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  Map<String, dynamic> boletaToMap(_i5.BoletaEntity? boleta) =>
      (super.noSuchMethod(
            Invocation.method(#boletaToMap, [boleta]),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.BoletaEntity mapToBoleta(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#mapToBoleta, [map]),
            returnValue: _FakeBoletaEntity_3(
              this,
              Invocation.method(#mapToBoleta, [map]),
            ),
            returnValueForMissingStub: _FakeBoletaEntity_3(
              this,
              Invocation.method(#mapToBoleta, [map]),
            ),
          )
          as _i5.BoletaEntity);

  @override
  _i13.BoletaTipo stringToBoletaTipo(String? tipo) =>
      (super.noSuchMethod(
            Invocation.method(#stringToBoletaTipo, [tipo]),
            returnValue: _i13.BoletaTipo.inicio,
            returnValueForMissingStub: _i13.BoletaTipo.inicio,
          )
          as _i13.BoletaTipo);
}
