// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/auth/domain/repositories/usuario_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cssayp_movil/auth/data/datasources/preferencias_data_source.dart'
    as _i11;
import 'package:cssayp_movil/auth/data/datasources/secure_storage_data_source.dart'
    as _i10;
import 'package:cssayp_movil/auth/data/datasources/usuario_data_source.dart'
    as _i3;
import 'package:cssayp_movil/auth/data/models/auth_response_models.dart' as _i5;
import 'package:cssayp_movil/auth/data/models/cambiar_password_response_models.dart'
    as _i9;
import 'package:cssayp_movil/auth/data/models/datos_usuario_response_models.dart'
    as _i8;
import 'package:cssayp_movil/auth/data/models/recuperar_password_response_models.dart'
    as _i7;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UsuarioDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuarioDataSource extends _i1.Mock implements _i3.UsuarioDataSource {
  MockUsuarioDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i4.Future<_i5.AuthResponseModel> autenticarUsuario(
    String? usuario,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#autenticarUsuario, [usuario, password]),
            returnValue: _i4.Future<_i5.AuthResponseModel>.value(
              _i6.dummyValue<_i5.AuthResponseModel>(
                this,
                Invocation.method(#autenticarUsuario, [usuario, password]),
              ),
            ),
          )
          as _i4.Future<_i5.AuthResponseModel>);

  @override
  _i4.Future<_i7.RecuperarResponseModel> recuperarPassword(
    String? tipoDocumento,
    String? nroDocumento,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recuperarPassword, [
              tipoDocumento,
              nroDocumento,
              email,
            ]),
            returnValue: _i4.Future<_i7.RecuperarResponseModel>.value(
              _i6.dummyValue<_i7.RecuperarResponseModel>(
                this,
                Invocation.method(#recuperarPassword, [
                  tipoDocumento,
                  nroDocumento,
                  email,
                ]),
              ),
            ),
          )
          as _i4.Future<_i7.RecuperarResponseModel>);

  @override
  _i4.Future<_i8.DatosUsuarioResponseModel> obtenerDatosUsuario(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerDatosUsuario, [token]),
            returnValue: _i4.Future<_i8.DatosUsuarioResponseModel>.value(
              _i6.dummyValue<_i8.DatosUsuarioResponseModel>(
                this,
                Invocation.method(#obtenerDatosUsuario, [token]),
              ),
            ),
          )
          as _i4.Future<_i8.DatosUsuarioResponseModel>);

  @override
  _i4.Future<_i9.CambiarPasswordResponseModel> cambiarPassword(
    String? token,
    String? passwordActual,
    String? passwordNueva,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cambiarPassword, [
              token,
              passwordActual,
              passwordNueva,
            ]),
            returnValue: _i4.Future<_i9.CambiarPasswordResponseModel>.value(
              _i6.dummyValue<_i9.CambiarPasswordResponseModel>(
                this,
                Invocation.method(#cambiarPassword, [
                  token,
                  passwordActual,
                  passwordNueva,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.CambiarPasswordResponseModel>);
}

/// A class which mocks [SecureStorageDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageDataSource extends _i1.Mock
    implements _i10.SecureStorageDataSource {
  MockSecureStorageDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> guardarToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#guardarToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> obtenerToken() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> eliminarToken() =>
      (super.noSuchMethod(
            Invocation.method(#eliminarToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> guardarValor(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#guardarValor, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> obtenerValor(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerValor, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [PreferenciasDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferenciasDataSource extends _i1.Mock
    implements _i11.PreferenciasDataSource {
  MockPreferenciasDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> guardarPreferenciaBiometria(bool? valor) =>
      (super.noSuchMethod(
            Invocation.method(#guardarPreferenciaBiometria, [valor]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> obtenerPreferenciaBiometria() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerPreferenciaBiometria, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> obtenerValor(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerValor, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> guardarValor(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#guardarValor, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
