// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/boletas/domain/usecases/buscar_boletas_inicio_pagadas_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cssayp_movil/auth/data/models/cambiar_password_response_models.dart'
    as _i11;
import 'package:cssayp_movil/auth/data/models/recuperar_password_response_models.dart'
    as _i9;
import 'package:cssayp_movil/auth/domain/entities/usuario_entity.dart' as _i8;
import 'package:cssayp_movil/auth/domain/repositories/usuario_repository.dart'
    as _i7;
import 'package:cssayp_movil/boletas/data/models/historial_boletas_response_models.dart'
    as _i3;
import 'package:cssayp_movil/boletas/data/models/paginated_response_model.dart'
    as _i4;
import 'package:cssayp_movil/boletas/domain/entities/boleta_entity.dart' as _i2;
import 'package:cssayp_movil/boletas/domain/repositories/boletas_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBoletaEntity_0 extends _i1.SmartFake implements _i2.BoletaEntity {
  _FakeBoletaEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistorialBoletasSuccessResponse_1 extends _i1.SmartFake
    implements _i3.HistorialBoletasSuccessResponse {
  _FakeHistorialBoletasSuccessResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePaginatedResponseModel_2 extends _i1.SmartFake
    implements _i4.PaginatedResponseModel {
  _FakePaginatedResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BoletasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoletasRepository extends _i1.Mock implements _i5.BoletasRepository {
  MockBoletasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.BoletaEntity> crearBoletaInicio({
    required String? caratula,
    required int? nroAfiliado,
    required double? monto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearBoletaInicio, [], {
              #caratula: caratula,
              #nroAfiliado: nroAfiliado,
              #monto: monto,
            }),
            returnValue: _i6.Future<_i2.BoletaEntity>.value(
              _FakeBoletaEntity_0(
                this,
                Invocation.method(#crearBoletaInicio, [], {
                  #caratula: caratula,
                  #nroAfiliado: nroAfiliado,
                  #monto: monto,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.BoletaEntity>);

  @override
  _i6.Future<_i2.BoletaEntity> crearBoletaFinalizacion({
    required int? nroAfiliado,
    required String? caratula,
    required int? idBoletaInicio,
    required double? monto,
    required DateTime? fechaRegulacion,
    required double? honorarios,
    required double? cantidadJus,
    required double? valorJus,
    int? nroExpediente,
    int? anioExpediente,
    int? cuij,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearBoletaFinalizacion, [], {
              #nroAfiliado: nroAfiliado,
              #caratula: caratula,
              #idBoletaInicio: idBoletaInicio,
              #monto: monto,
              #fechaRegulacion: fechaRegulacion,
              #honorarios: honorarios,
              #cantidadJus: cantidadJus,
              #valorJus: valorJus,
              #nroExpediente: nroExpediente,
              #anioExpediente: anioExpediente,
              #cuij: cuij,
            }),
            returnValue: _i6.Future<_i2.BoletaEntity>.value(
              _FakeBoletaEntity_0(
                this,
                Invocation.method(#crearBoletaFinalizacion, [], {
                  #nroAfiliado: nroAfiliado,
                  #caratula: caratula,
                  #idBoletaInicio: idBoletaInicio,
                  #monto: monto,
                  #fechaRegulacion: fechaRegulacion,
                  #honorarios: honorarios,
                  #cantidadJus: cantidadJus,
                  #valorJus: valorJus,
                  #nroExpediente: nroExpediente,
                  #anioExpediente: anioExpediente,
                  #cuij: cuij,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.BoletaEntity>);

  @override
  _i6.Future<_i3.HistorialBoletasSuccessResponse> obtenerHistorialBoletas(
    int? nroAfiliado, {
    int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #obtenerHistorialBoletas,
              [nroAfiliado],
              {#page: page},
            ),
            returnValue: _i6.Future<_i3.HistorialBoletasSuccessResponse>.value(
              _FakeHistorialBoletasSuccessResponse_1(
                this,
                Invocation.method(
                  #obtenerHistorialBoletas,
                  [nroAfiliado],
                  {#page: page},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.HistorialBoletasSuccessResponse>);

  @override
  _i6.Future<_i4.PaginatedResponseModel> buscarBoletasInicioPagadas({
    required int? nroAfiliado,
    int? page = 1,
    String? caratulaBuscada,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buscarBoletasInicioPagadas, [], {
              #nroAfiliado: nroAfiliado,
              #page: page,
              #caratulaBuscada: caratulaBuscada,
            }),
            returnValue: _i6.Future<_i4.PaginatedResponseModel>.value(
              _FakePaginatedResponseModel_2(
                this,
                Invocation.method(#buscarBoletasInicioPagadas, [], {
                  #nroAfiliado: nroAfiliado,
                  #page: page,
                  #caratulaBuscada: caratulaBuscada,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.PaginatedResponseModel>);
}

/// A class which mocks [UsuarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuarioRepository extends _i1.Mock implements _i7.UsuarioRepository {
  MockUsuarioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i8.UsuarioEntity?> autenticar(
    String? usuario,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#autenticar, [usuario, password]),
            returnValue: _i6.Future<_i8.UsuarioEntity?>.value(),
          )
          as _i6.Future<_i8.UsuarioEntity?>);

  @override
  _i6.Future<bool> estaAutenticado() =>
      (super.noSuchMethod(
            Invocation.method(#estaAutenticado, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> cerrarSesion() =>
      (super.noSuchMethod(
            Invocation.method(#cerrarSesion, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i8.UsuarioEntity?> obtenerUsuarioActual() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerUsuarioActual, []),
            returnValue: _i6.Future<_i8.UsuarioEntity?>.value(),
          )
          as _i6.Future<_i8.UsuarioEntity?>);

  @override
  _i6.Future<_i9.RecuperarResponseModel> recuperarPassword(
    String? tipoDocumento,
    String? nroDocumento,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recuperarPassword, [
              tipoDocumento,
              nroDocumento,
              email,
            ]),
            returnValue: _i6.Future<_i9.RecuperarResponseModel>.value(
              _i10.dummyValue<_i9.RecuperarResponseModel>(
                this,
                Invocation.method(#recuperarPassword, [
                  tipoDocumento,
                  nroDocumento,
                  email,
                ]),
              ),
            ),
          )
          as _i6.Future<_i9.RecuperarResponseModel>);

  @override
  _i6.Future<_i11.CambiarPasswordResponseModel> cambiarPassword(
    String? passwordActual,
    String? passwordNueva,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cambiarPassword, [
              passwordActual,
              passwordNueva,
            ]),
            returnValue: _i6.Future<_i11.CambiarPasswordResponseModel>.value(
              _i10.dummyValue<_i11.CambiarPasswordResponseModel>(
                this,
                Invocation.method(#cambiarPassword, [
                  passwordActual,
                  passwordNueva,
                ]),
              ),
            ),
          )
          as _i6.Future<_i11.CambiarPasswordResponseModel>);
}
