// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/comprobantes/domain/usecases/compartir_comprobante_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cssayp_movil/auth/auth.dart' as _i3;
import 'package:cssayp_movil/comprobantes/comprobantes.dart' as _i5;
import 'package:cssayp_movil/shared/services/pdf_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:share_plus/share_plus.dart' as _i8;
import 'package:share_plus_platform_interface/share_plus_platform_interface.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePdfService_0 extends _i1.SmartFake implements _i2.PdfService {
  _FakePdfService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsuarioRepository_1 extends _i1.SmartFake
    implements _i3.UsuarioRepository {
  _FakeUsuarioRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShareResult_2 extends _i1.SmartFake implements _i4.ShareResult {
  _FakeShareResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GenerarComprobanteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerarComprobanteUseCase extends _i1.Mock
    implements _i5.GenerarComprobanteUseCase {
  @override
  _i2.PdfService get pdfService =>
      (super.noSuchMethod(
            Invocation.getter(#pdfService),
            returnValue: _FakePdfService_0(
              this,
              Invocation.getter(#pdfService),
            ),
            returnValueForMissingStub: _FakePdfService_0(
              this,
              Invocation.getter(#pdfService),
            ),
          )
          as _i2.PdfService);

  @override
  _i3.UsuarioRepository get usuarioRepository =>
      (super.noSuchMethod(
            Invocation.getter(#usuarioRepository),
            returnValue: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
            returnValueForMissingStub: _FakeUsuarioRepository_1(
              this,
              Invocation.getter(#usuarioRepository),
            ),
          )
          as _i3.UsuarioRepository);

  @override
  _i6.Future<String> execute(_i5.ComprobanteEntity? comprobante) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [comprobante]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#execute, [comprobante]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#execute, [comprobante]),
              ),
            ),
          )
          as _i6.Future<String>);
}

/// A class which mocks [SharePlus].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharePlus extends _i1.Mock implements _i8.SharePlus {
  @override
  _i6.Future<_i4.ShareResult> share(_i4.ShareParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#share, [params]),
            returnValue: _i6.Future<_i4.ShareResult>.value(
              _FakeShareResult_2(this, Invocation.method(#share, [params])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.ShareResult>.value(
              _FakeShareResult_2(this, Invocation.method(#share, [params])),
            ),
          )
          as _i6.Future<_i4.ShareResult>);
}
