// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/comprobantes/domain/usecases/generar_comprobante_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cssayp_movil/auth/auth.dart' as _i5;
import 'package:cssayp_movil/comprobantes/comprobantes.dart' as _i4;
import 'package:cssayp_movil/shared/services/pdf_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfService extends _i1.Mock implements _i2.PdfService {
  @override
  _i3.Future<String> generarPdfComprobante({
    required _i4.ComprobanteEntity? comprobante,
    required _i5.UsuarioEntity? usuario,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generarPdfComprobante, [], {
              #comprobante: comprobante,
              #usuario: usuario,
            }),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generarPdfComprobante, [], {
                  #comprobante: comprobante,
                  #usuario: usuario,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generarPdfComprobante, [], {
                  #comprobante: comprobante,
                  #usuario: usuario,
                }),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [UsuarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuarioRepository extends _i1.Mock implements _i5.UsuarioRepository {
  @override
  _i3.Future<_i5.UsuarioEntity?> autenticar(
    String? usuario,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#autenticar, [usuario, password]),
            returnValue: _i3.Future<_i5.UsuarioEntity?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.UsuarioEntity?>.value(),
          )
          as _i3.Future<_i5.UsuarioEntity?>);

  @override
  _i3.Future<bool> estaAutenticado() =>
      (super.noSuchMethod(
            Invocation.method(#estaAutenticado, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> cerrarSesion() =>
      (super.noSuchMethod(
            Invocation.method(#cerrarSesion, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.UsuarioEntity?> obtenerUsuarioActual() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerUsuarioActual, []),
            returnValue: _i3.Future<_i5.UsuarioEntity?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.UsuarioEntity?>.value(),
          )
          as _i3.Future<_i5.UsuarioEntity?>);

  @override
  _i3.Future<_i5.RecuperarResponseModel> recuperarPassword(
    String? tipoDocumento,
    String? nroDocumento,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recuperarPassword, [
              tipoDocumento,
              nroDocumento,
              email,
            ]),
            returnValue: _i3.Future<_i5.RecuperarResponseModel>.value(
              _i6.dummyValue<_i5.RecuperarResponseModel>(
                this,
                Invocation.method(#recuperarPassword, [
                  tipoDocumento,
                  nroDocumento,
                  email,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.RecuperarResponseModel>.value(
                  _i6.dummyValue<_i5.RecuperarResponseModel>(
                    this,
                    Invocation.method(#recuperarPassword, [
                      tipoDocumento,
                      nroDocumento,
                      email,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i5.RecuperarResponseModel>);

  @override
  _i3.Future<_i5.CambiarPasswordResponseModel> cambiarPassword(
    String? passwordActual,
    String? passwordNueva,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cambiarPassword, [
              passwordActual,
              passwordNueva,
            ]),
            returnValue: _i3.Future<_i5.CambiarPasswordResponseModel>.value(
              _i6.dummyValue<_i5.CambiarPasswordResponseModel>(
                this,
                Invocation.method(#cambiarPassword, [
                  passwordActual,
                  passwordNueva,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.CambiarPasswordResponseModel>.value(
                  _i6.dummyValue<_i5.CambiarPasswordResponseModel>(
                    this,
                    Invocation.method(#cambiarPassword, [
                      passwordActual,
                      passwordNueva,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i5.CambiarPasswordResponseModel>);
}
