// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/pagos/domain/usecases/pagar_con_red_link_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cssayp_movil/pagos/data/models/red_link_payment_response_model.dart'
    as _i2;
import 'package:cssayp_movil/pagos/domain/repositories/red_link_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRedLinkPaymentResponseModel_0 extends _i1.SmartFake
    implements _i2.RedLinkPaymentResponseModel {
  _FakeRedLinkPaymentResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRedLinkPaymentStatusModel_1 extends _i1.SmartFake
    implements _i2.RedLinkPaymentStatusModel {
  _FakeRedLinkPaymentStatusModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RedLinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRedLinkRepository extends _i1.Mock implements _i3.RedLinkRepository {
  MockRedLinkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RedLinkPaymentResponseModel> generarUrlPago({
    required int? idBoleta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generarUrlPago, [], {#idBoleta: idBoleta}),
            returnValue: _i4.Future<_i2.RedLinkPaymentResponseModel>.value(
              _FakeRedLinkPaymentResponseModel_0(
                this,
                Invocation.method(#generarUrlPago, [], {#idBoleta: idBoleta}),
              ),
            ),
          )
          as _i4.Future<_i2.RedLinkPaymentResponseModel>);

  @override
  _i4.Future<_i2.RedLinkPaymentStatusModel> verificarEstadoPago({
    required int? idBoleta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verificarEstadoPago, [], {#idBoleta: idBoleta}),
            returnValue: _i4.Future<_i2.RedLinkPaymentStatusModel>.value(
              _FakeRedLinkPaymentStatusModel_1(
                this,
                Invocation.method(#verificarEstadoPago, [], {
                  #idBoleta: idBoleta,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.RedLinkPaymentStatusModel>);
}
