// Mocks generated by Mockito 5.4.6 from annotations
// in cssayp_movil/test/pagos/domain/usecases/pagar_con_payway_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cssayp_movil/pagos/pagos.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResultadoPagoModel_0 extends _i1.SmartFake
    implements _i2.ResultadoPagoModel {
  _FakeResultadoPagoModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaywayRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaywayRepository extends _i1.Mock implements _i2.PaywayRepository {
  MockPaywayRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ResultadoPagoModel> pagar({
    required List<_i2.BoletaAPagarEntity>? boletas,
    required _i2.DatosTarjetaModel? datosTarjeta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pagar, [], {
              #boletas: boletas,
              #datosTarjeta: datosTarjeta,
            }),
            returnValue: _i3.Future<_i2.ResultadoPagoModel>.value(
              _FakeResultadoPagoModel_0(
                this,
                Invocation.method(#pagar, [], {
                  #boletas: boletas,
                  #datosTarjeta: datosTarjeta,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.ResultadoPagoModel>);

  @override
  _i3.Future<void> actualizarEstadoLocalBoleta(
    _i2.BoletaAPagarEntity? boleta,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarEstadoLocalBoleta, [boleta]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
